name: Monthly issue metrics
on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read

    steps:

    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: contoso-com.mail.protection.outlook.com
        server_port: 25
        username: ${{secrets.EMAIL}}
        # password: ${{secrets.EMAIL_PASSWORD}}
        subject: TEST TEST Github Actions job result
        to: ${{secrets.EMAIL}}
        # from: BDX Team
        body: test | TEST | test
        convert_markdown: true
