name: Test Notifications to Slack
on: workflow_dispatch

jobs:
  notifications:
    name: Send Notifications
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
            "Notification Type": "Pull Request"
            "Notification Link": "Link Link"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
