name: Send GitHub Stats to CloudWatch
on: workflow_dispatch

jobs:
  send-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.9'

      - name: Install Dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install requests boto3

      - name: Fetch GitHub Repository Stats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ secrets.REPO_OWNER }}
          REPO_NAME: 'simple-ecs-application'
        run:
          python fetch_stats.py

      - name: Upload stats to AWS Cloudwatch
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          NAMESPACE: ${{ secrets.NAMESPACE }}
        run:
          python upload_to_cloudwatch_metrics.py
        
      
  
